# Generated by Django 4.2.4 on 2023-08-08 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_author_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='rating_comm',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='rating_post',
            new_name='rating',
        ),
    ]
